# Get info
GET http://localhost:3001/info
###

# Get all people
GET http://localhost:3001/api/people
###

# Get person with id
GET http://localhost:3001/api/people/640eec0b76d168ffaef34b29
###

# Delete person with id
DELETE http://localhost:3001/api/people/640eec0b76d168ffaef34b29
###

# Add a new person
POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "hé",
    "number": "01 23"
}
###

# Update person number
PUT http://localhost:3001/api/people/640eec0b76d168ffaef34b29
Content-Type: application/json

{
    "name": "Roger Petit",
    "number": "01 23 45 67 89"
}